name: Daily Empty Commit

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  empty_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create Empty Commit
        run: |
          git commit --allow-empty -m "Daily empty commit"
          git push
