name: Keep App Awake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: goat
        run: curl -s https://wengoat.streamlit.app/

      - name: ping cairngorms
        run: curl -s https://cairngorms.streamlit.app/

